SetVisible
SetCustomSize   ( 24` 24` )
SetAlpha    ( 240` )
SetTexelOffset  ( 00000000 FFFFFFFF )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha    ( 220` )
SetTexelOffset  ( FFFFFFFD FFFFFFFD )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha    ( 200` )
SetTexelOffset  ( FFFFFFFA FFFFFFFB )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha    ( 170` )
SetTexelOffset  ( FFFFFFF8 FFFFFFFA )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha    ( 120` )
SetTexelOffset  ( FFFFFFF6 FFFFFFFB )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha    ( 80` )
SetTexelOffset  ( FFFFFFF4 FFFFFFFD )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha    ( 50` )
SetTexelOffset  ( FFFFFFF3 00000000 )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha    ( 30` )
SetTexelOffset  ( FFFFFFF2 00000004 )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetTexelOffset  ( FFFFFFF1 00000009 )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetTexelOffset  ( FFFFFFF1 0000000F )
SetCI       ( 1` ~ImageCI:ui/battle/status/bonus_smash )
End
