SetTexelOffset  ( 00000008 00000008 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_0 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_1 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_2 )
SetIcon     ( 2` ~ImageIcon:item/anim/shimmer_6 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_2 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_3 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_6 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_4 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_6 )
SetIcon     ( 1` ~ImageIcon:item/anim/shimmer_5 )
SetIcon     ( 16` ~ImageIcon:item/anim/shimmer_6 )
End
