SetVisible
SetCustomSize   ( 16` 16` )
SetAlpha    ( 30` )
SetTexelOffset  ( 0000000A FFFFFFF6 )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 50` )
SetTexelOffset  ( 00000008 FFFFFFF8 )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 80` )
SetTexelOffset  ( 00000006 FFFFFFFA )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 120` )
SetTexelOffset  ( 00000005 FFFFFFFB )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 170` )
SetTexelOffset  ( 00000004 FFFFFFFC )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 200` )
SetTexelOffset  ( 00000003 FFFFFFFD )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 220` )
SetTexelOffset  ( 00000002 FFFFFFFE )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 240` )
SetTexelOffset  ( 00000001 FFFFFFFF )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
SetAlpha    ( 255` )
SetTexelOffset  ( 00000000 00000000 )
SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
Loop
	SetCI       ( 24` ~ImageCI:ui/battle/status/static_5 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_8 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_8 )
	SetCI       ( 49` ~ImageCI:ui/battle/status/static_5 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_8 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_5 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_7 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_6 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_7 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_6 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_7 )
	SetCI       ( 1` ~ImageCI:ui/battle/status/static_6 )
Restart
End
